language: php

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - php ./vendor/bin/phpunit -c phpunit.sample.xml
